version: '3.9'

services:
  app:
    build: 
      context: .
      target: ${STAGE}
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    container_name: app
    ports:
      - ${PORT}:${PORT}
    environment:
      BASE_URL: ${BASE_URL}
      DB_NAME: ${DB_NAME}
      DB_TYPE: ${DB_TYPE}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: "${DB_NAME}-db"
